version: '3.8'
services:
  # 1. O serviço do Banco de Dados
  db:
    image: postgres:15-alpine  # Imagem oficial do Postgres
    container_name: postgres_db
  environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # 2. O serviço da API
  api:
    container_name: fastapi_api
    build: .
    ports:
      - "8000:8000"
    environment:
      # URL de conexão que o Python vai usar.
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      # Garante que o contêiner do postgres seja iniciado antes da api (evita erros rs)
      - db
volumes:
  postgres_data: